# app/utils/constants.py

class DBConstants:
    DB_USERNAME = 'DB_USERNAME'
    DB_PASSWORD = 'DB_PASSWORD'
    DB_HOST = 'DB_HOST'
    DB_PORT = 'DB_PORT'
    DB_NAME = 'DB_NAME'
    DEFAULT_HOST = 'localhost'
    DEFAULT_PORT = 3306
    SQLALCHEMY_DATABASE_URI = 'SQLALCHEMY_DATABASE_URI'
    SQLALCHEMY_TRACK_MODIFICATIONS = 'SQLALCHEMY_TRACK_MODIFICATIONS'